import type { Metadata } from "next";

import "./globals.css";
import { Libre_Franklin } from "next/font/google";

const libreFranklin = Libre_Franklin({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // Add the weights you want to use
  variable: "--font-libre-franklin", // Optional: for Tailwind CSS integration
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={libreFranklin.variable}>
      <body className={libreFranklin.className}>{children}</body>
    </html>
  );
}
